// =============================================================
// TNM Transcript Generator
// Fetches every message in a ticket channel and writes a self-contained,
// readable HTML file to /transcripts, then returns it as a Discord attachment.
// =============================================================

const fs = require('fs');
const path = require('path');
const { AttachmentBuilder } = require('discord.js');

const TRANSCRIPT_DIR = path.join(__dirname, '..', '..', 'transcripts');
if (!fs.existsSync(TRANSCRIPT_DIR)) fs.mkdirSync(TRANSCRIPT_DIR, { recursive: true });

function escapeHtml(str = '') {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Builds an HTML transcript of every message in `channel` and saves it to disk.
 * Returns { filePath, attachment } where attachment is a discord.js AttachmentBuilder.
 */
async function generateTranscript(channel) {
  const allMessages = [];
  let lastId;

  // Paginate backward through channel history (Discord caps fetch at 100/request).
  for (;;) {
    const batch = await channel.messages.fetch({ limit: 100, before: lastId });
    if (batch.size === 0) break;
    allMessages.push(...batch.values());
    lastId = batch.last().id;
    if (batch.size < 100) break;
  }

  allMessages.reverse(); // oldest first

  const rows = allMessages
    .map((msg) => {
      const time = new Date(msg.createdTimestamp).toLocaleString('en-US');
      const author = escapeHtml(msg.author?.tag || 'Unknown User');
      const content = escapeHtml(msg.content || '') || '<i>(no text content)</i>';
      const attachments = msg.attachments
        .map((a) => `<div class="attachment"><a href="${a.url}" target="_blank">${escapeHtml(a.name)}</a></div>`)
        .join('');
      return `
        <div class="message">
          <div class="meta"><span class="author">${author}</span><span class="time">${time}</span></div>
          <div class="content">${content}</div>
          ${attachments}
        </div>`;
    })
    .join('\n');

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Transcript - ${escapeHtml(channel.name)}</title>
<style>
  body { background:#0d0d0d; color:#f2f2f2; font-family: 'Segoe UI', Arial, sans-serif; padding: 24px; }
  h1 { border-bottom: 2px solid #fff; padding-bottom: 8px; }
  .message { border-bottom: 1px solid #262626; padding: 10px 0; }
  .meta { display:flex; gap:12px; margin-bottom: 4px; }
  .author { font-weight: 700; color:#ffffff; }
  .time { color:#888; font-size: 12px; }
  .content { white-space: pre-wrap; word-break: break-word; color:#e0e0e0; }
  .attachment { margin-top: 4px; }
  .attachment a { color:#9ecbff; }
  footer { margin-top: 24px; color:#666; font-size: 12px; }
</style>
</head>
<body>
  <h1>TNM Ticket Transcript — #${escapeHtml(channel.name)}</h1>
  ${rows || '<p>No messages were sent in this ticket.</p>'}
  <footer>Generated by TNM • Powered by TNM</footer>
</body>
</html>`;

  const fileName = `transcript-${channel.id}-${Date.now()}.html`;
  const filePath = path.join(TRANSCRIPT_DIR, fileName);
  fs.writeFileSync(filePath, html, 'utf8');

  const attachment = new AttachmentBuilder(filePath, { name: fileName });
  return { filePath, attachment };
}

module.exports = { generateTranscript };
